### PR TITLE
Frontend/Backend/DB: Notification support for like, comment and quiz reminders

### PR DESCRIPTION
**Pull request by gao-ti**
## Description
This PR includes
- notifications of likes
- notifications of comments
- notifications of quiz reminders

## Future work

- Now quiz reminders appear regardless of when I last took it
- Checked/Unchecked notifications cannot be distinguished
- Do not redirect to the post where comments/likes are

### CODE REVIEW

**Comment by gao-ti** [comment]
image

**Review by davidfortuoso-ti — APPROVED** [review]
Works for me, good job with the notifications

**Comment by davidfortuoso-ti** [comment]
One suggestion: Close notification dropdown when user clicks outside of the notification box.

**Review by arsen-ti — APPROVED** [review]
all good

**Pull request merged**
